[package]
name = "bytes-radar"
version = "0.1.0"
edition = "2024"
authors = ["ProgramZmh <zmh@lightxi.com>"]
description = "A tool for analyzing code statistics from remote repositories with hyper-fast performance"
license = "Apache-2.0"
repository = "https://github.com/zmh-program/bytes-radar"
keywords = ["cloc", "code analysis", "wasm", "remote", "cli"]

[features]
default = ["cli"]
cli = ["dep:colored", "dep:env_logger", "dep:clap", "dep:indicatif"]

[dependencies]
once_cell = "1.21"
anyhow = "1.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.6"
log = "0.4"
reqwest = { version = "0.12", features = ["stream", "rustls-tls"], default-features = false }
tar = "0.4"
flate2 = "1.0"
tokio = { version = "1.46", features = ["full"] }
futures-util = "0.3"
bytes = "1.5"

# CLI dependencies (optional)
colored = { version = "2.1", optional = true }
env_logger = { version = "0.11", optional = true }
clap = { version = "4.5", features = ["derive"], optional = true }
indicatif = { version = "0.17", optional = true }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
