name = "bytes-radar"
main = "bytes-radar.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "BYTES_RADAR", class_name = "BytesRadar" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BytesRadar"]

[observability]
enabled = true
head_sampling_rate = 1

[env.production]
name = "bytes-radar-prod"

[env.staging]
name = "bytes-radar-staging"

compatibility_flags = ["nodejs_compat"]
